<?php

/**
 * @file
 * Contains camposlo.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function camposlo_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the camposlo module.
    case 'help.page.camposlo':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal Camp Oslo specific module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function camposlo_theme() {
  $theme = [
    'camposlo-price-block' => [
      'variables' => ['prices' => []],
    ],
    'camposlo-contact-block' => [
      'variables' => [],
    ],
  ];

  return $theme;
}
